### ISSUE TITLE
MorePowerTool no longer available

### ISSUE THREAD

**Issue by royalgraphx** [perez987/6600XT-on-macOS-with-PowerPlayTable-to-SSDT-or-config.plist#3]
What am I supposed to use when MPT is no longer available? Where do I get a safe unmodified archive of it? as even the installer isn't offline, it downloads a "MorePowerToolCurve_1_3_8_final.zip" which again is also no longer available.

**Comment by royalgraphx** [comment]
resolved, the websites set up in a blog manner, and the links are all broken unless you find the proper executable.

https://www.igorslab.de/installer/MorePowerTool_Setup.exe

**Comment by perez987** [comment]
Sorry @royalgraphx for my delayed answer. 
This issue had gone unnoticed by me. I just read it now.

I see that Igor's Lab site has changed its design, as you say, and that he has separated downloads of stable versions from beta versions. It can be a bit complicated to get to the MorePowerTool download. At least it's still available.

Thank you for your notice even though it is very late.
